(define compose (lambda (f g) (lambda (x) (f (g x)))))
(define const (lambda (x) (lambda (y) x)))
(define curry (lambda (f x) (lambda (y) (f x y))))
(define flip (lambda (f) (lambda (x y) (f y x))))
(define id (lambda (x) x))
